openapi: 3.0.0
info:
  title: Influencer Chatbot API
  version: 1.0.0
paths:
  /chat:
    post:
      summary: "Send a message to the chatbot"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        "200":
          description: "Chatbot response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
